# Site Meta
title: "Endless Coffee Co."
phase: "alpha"
version: "0.1"
description: |
  We're a group of people who are passionate about sourcing and roasting coffee sustainably and thoughtfully. We seek to produce coffees that accentuate and celebrate the idiosyncrasies of the regions and farms from which we source.

  Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.

  Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?

  ~ Joe, Josh, Olivia and Izzy
author:

# URL Stuff
baseurl: "" # Set the baseurl to the name of your Github repo when deploying with Github Pages
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exclude
exclude: [node_modules, gulpfile.js, Gemfile, Gemfile.lock, package.json, yarn.lock, README.md, .gitignore]
